//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 10:39:11 AM BST 
//


package google.geocodingservice.geocoder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Status">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="request" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Placemark">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="AddressDetails">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Country">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="CountryNameCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                 &lt;element name="AdministrativeArea">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                           &lt;element name="SubAdministrativeArea">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                                     &lt;element name="Locality">
 *                                                                       &lt;complexType>
 *                                                                         &lt;complexContent>
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                             &lt;sequence>
 *                                                                               &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                                               &lt;element name="Thoroughfare">
 *                                                                                 &lt;complexType>
 *                                                                                   &lt;complexContent>
 *                                                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                                       &lt;sequence>
 *                                                                                         &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                                                       &lt;/sequence>
 *                                                                                     &lt;/restriction>
 *                                                                                   &lt;/complexContent>
 *                                                                                 &lt;/complexType>
 *                                                                               &lt;/element>
 *                                                                               &lt;element name="PostalCode">
 *                                                                                 &lt;complexType>
 *                                                                                   &lt;complexContent>
 *                                                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                                       &lt;sequence>
 *                                                                                         &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                                                       &lt;/sequence>
 *                                                                                     &lt;/restriction>
 *                                                                                   &lt;/complexContent>
 *                                                                                 &lt;/complexType>
 *                                                                               &lt;/element>
 *                                                                             &lt;/sequence>
 *                                                                           &lt;/restriction>
 *                                                                         &lt;/complexContent>
 *                                                                       &lt;/complexType>
 *                                                                     &lt;/element>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="Accuracy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Point">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "kml")
public class Kml {

    @XmlElement(name = "Response", required = true)
    protected Kml.Response response;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Kml.Response }
     *     
     */
    public Kml.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kml.Response }
     *     
     */
    public void setResponse(Kml.Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Status">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="request" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Placemark">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="AddressDetails">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Country">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="CountryNameCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                       &lt;element name="AdministrativeArea">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                 &lt;element name="SubAdministrativeArea">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                           &lt;element name="Locality">
     *                                                             &lt;complexType>
     *                                                               &lt;complexContent>
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                   &lt;sequence>
     *                                                                     &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                                     &lt;element name="Thoroughfare">
     *                                                                       &lt;complexType>
     *                                                                         &lt;complexContent>
     *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                             &lt;sequence>
     *                                                                               &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                                             &lt;/sequence>
     *                                                                           &lt;/restriction>
     *                                                                         &lt;/complexContent>
     *                                                                       &lt;/complexType>
     *                                                                     &lt;/element>
     *                                                                     &lt;element name="PostalCode">
     *                                                                       &lt;complexType>
     *                                                                         &lt;complexContent>
     *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                             &lt;sequence>
     *                                                                               &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                                                                             &lt;/sequence>
     *                                                                           &lt;/restriction>
     *                                                                         &lt;/complexContent>
     *                                                                       &lt;/complexType>
     *                                                                     &lt;/element>
     *                                                                   &lt;/sequence>
     *                                                                 &lt;/restriction>
     *                                                               &lt;/complexContent>
     *                                                             &lt;/complexType>
     *                                                           &lt;/element>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="Accuracy" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Point">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "status",
        "placemark"
    })
    public static class Response {

        @XmlElement(required = true)
        protected Object name;
        @XmlElement(name = "Status", required = true)
        protected Kml.Response.Status status;
        @XmlElement(name = "Placemark", required = true)
        protected Kml.Response.Placemark placemark;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setName(Object value) {
            this.name = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link Kml.Response.Status }
         *     
         */
        public Kml.Response.Status getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link Kml.Response.Status }
         *     
         */
        public void setStatus(Kml.Response.Status value) {
            this.status = value;
        }

        /**
         * Gets the value of the placemark property.
         * 
         * @return
         *     possible object is
         *     {@link Kml.Response.Placemark }
         *     
         */
        public Kml.Response.Placemark getPlacemark() {
            return placemark;
        }

        /**
         * Sets the value of the placemark property.
         * 
         * @param value
         *     allowed object is
         *     {@link Kml.Response.Placemark }
         *     
         */
        public void setPlacemark(Kml.Response.Placemark value) {
            this.placemark = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="AddressDetails">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Country">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="CountryNameCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                             &lt;element name="AdministrativeArea">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                       &lt;element name="SubAdministrativeArea">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                                 &lt;element name="Locality">
         *                                                   &lt;complexType>
         *                                                     &lt;complexContent>
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                         &lt;sequence>
         *                                                           &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                                           &lt;element name="Thoroughfare">
         *                                                             &lt;complexType>
         *                                                               &lt;complexContent>
         *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                                   &lt;sequence>
         *                                                                     &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                                                   &lt;/sequence>
         *                                                                 &lt;/restriction>
         *                                                               &lt;/complexContent>
         *                                                             &lt;/complexType>
         *                                                           &lt;/element>
         *                                                           &lt;element name="PostalCode">
         *                                                             &lt;complexType>
         *                                                               &lt;complexContent>
         *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                                   &lt;sequence>
         *                                                                     &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                                                                   &lt;/sequence>
         *                                                                 &lt;/restriction>
         *                                                               &lt;/complexContent>
         *                                                             &lt;/complexType>
         *                                                           &lt;/element>
         *                                                         &lt;/sequence>
         *                                                       &lt;/restriction>
         *                                                     &lt;/complexContent>
         *                                                   &lt;/complexType>
         *                                                 &lt;/element>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="Accuracy" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Point">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address",
            "addressDetails",
            "point"
        })
        public static class Placemark {

            @XmlElement(required = true)
            protected Object address;
            @XmlElement(name = "AddressDetails", required = true)
            protected Kml.Response.Placemark.AddressDetails addressDetails;
            @XmlElement(name = "Point", required = true)
            protected Kml.Response.Placemark.Point point;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setAddress(Object value) {
                this.address = value;
            }

            /**
             * Gets the value of the addressDetails property.
             * 
             * @return
             *     possible object is
             *     {@link Kml.Response.Placemark.AddressDetails }
             *     
             */
            public Kml.Response.Placemark.AddressDetails getAddressDetails() {
                return addressDetails;
            }

            /**
             * Sets the value of the addressDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link Kml.Response.Placemark.AddressDetails }
             *     
             */
            public void setAddressDetails(Kml.Response.Placemark.AddressDetails value) {
                this.addressDetails = value;
            }

            /**
             * Gets the value of the point property.
             * 
             * @return
             *     possible object is
             *     {@link Kml.Response.Placemark.Point }
             *     
             */
            public Kml.Response.Placemark.Point getPoint() {
                return point;
            }

            /**
             * Sets the value of the point property.
             * 
             * @param value
             *     allowed object is
             *     {@link Kml.Response.Placemark.Point }
             *     
             */
            public void setPoint(Kml.Response.Placemark.Point value) {
                this.point = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Country">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="CountryNameCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                   &lt;element name="AdministrativeArea">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                             &lt;element name="SubAdministrativeArea">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                                       &lt;element name="Locality">
             *                                         &lt;complexType>
             *                                           &lt;complexContent>
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                               &lt;sequence>
             *                                                 &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                                                 &lt;element name="Thoroughfare">
             *                                                   &lt;complexType>
             *                                                     &lt;complexContent>
             *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                                         &lt;sequence>
             *                                                           &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                                                         &lt;/sequence>
             *                                                       &lt;/restriction>
             *                                                     &lt;/complexContent>
             *                                                   &lt;/complexType>
             *                                                 &lt;/element>
             *                                                 &lt;element name="PostalCode">
             *                                                   &lt;complexType>
             *                                                     &lt;complexContent>
             *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                                         &lt;sequence>
             *                                                           &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *                                                         &lt;/sequence>
             *                                                       &lt;/restriction>
             *                                                     &lt;/complexContent>
             *                                                   &lt;/complexType>
             *                                                 &lt;/element>
             *                                               &lt;/sequence>
             *                                             &lt;/restriction>
             *                                           &lt;/complexContent>
             *                                         &lt;/complexType>
             *                                       &lt;/element>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="Accuracy" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "country"
            })
            public static class AddressDetails {

                @XmlElement(name = "Country", required = true)
                protected Kml.Response.Placemark.AddressDetails.Country country;
                @XmlAttribute(name = "Accuracy")
                protected String accuracy;

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Kml.Response.Placemark.AddressDetails.Country }
                 *     
                 */
                public Kml.Response.Placemark.AddressDetails.Country getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Kml.Response.Placemark.AddressDetails.Country }
                 *     
                 */
                public void setCountry(Kml.Response.Placemark.AddressDetails.Country value) {
                    this.country = value;
                }

                /**
                 * Gets the value of the accuracy property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccuracy() {
                    return accuracy;
                }

                /**
                 * Sets the value of the accuracy property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccuracy(String value) {
                    this.accuracy = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="CountryNameCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *         &lt;element name="AdministrativeArea">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                   &lt;element name="SubAdministrativeArea">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                             &lt;element name="Locality">
                 *                               &lt;complexType>
                 *                                 &lt;complexContent>
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                     &lt;sequence>
                 *                                       &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                                       &lt;element name="Thoroughfare">
                 *                                         &lt;complexType>
                 *                                           &lt;complexContent>
                 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                               &lt;sequence>
                 *                                                 &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                                               &lt;/sequence>
                 *                                             &lt;/restriction>
                 *                                           &lt;/complexContent>
                 *                                         &lt;/complexType>
                 *                                       &lt;/element>
                 *                                       &lt;element name="PostalCode">
                 *                                         &lt;complexType>
                 *                                           &lt;complexContent>
                 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                               &lt;sequence>
                 *                                                 &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                 *                                               &lt;/sequence>
                 *                                             &lt;/restriction>
                 *                                           &lt;/complexContent>
                 *                                         &lt;/complexType>
                 *                                       &lt;/element>
                 *                                     &lt;/sequence>
                 *                                   &lt;/restriction>
                 *                                 &lt;/complexContent>
                 *                               &lt;/complexType>
                 *                             &lt;/element>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "countryNameCode",
                    "administrativeArea"
                })
                public static class Country {

                    @XmlElement(name = "CountryNameCode", required = true)
                    protected Object countryNameCode;
                    @XmlElement(name = "AdministrativeArea", required = true)
                    protected Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea administrativeArea;

                    /**
                     * Gets the value of the countryNameCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Object }
                     *     
                     */
                    public Object getCountryNameCode() {
                        return countryNameCode;
                    }

                    /**
                     * Sets the value of the countryNameCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Object }
                     *     
                     */
                    public void setCountryNameCode(Object value) {
                        this.countryNameCode = value;
                    }

                    /**
                     * Gets the value of the administrativeArea property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea }
                     *     
                     */
                    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea getAdministrativeArea() {
                        return administrativeArea;
                    }

                    /**
                     * Sets the value of the administrativeArea property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea }
                     *     
                     */
                    public void setAdministrativeArea(Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea value) {
                        this.administrativeArea = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="AdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *         &lt;element name="SubAdministrativeArea">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *                   &lt;element name="Locality">
                     *                     &lt;complexType>
                     *                       &lt;complexContent>
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                           &lt;sequence>
                     *                             &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *                             &lt;element name="Thoroughfare">
                     *                               &lt;complexType>
                     *                                 &lt;complexContent>
                     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                                     &lt;sequence>
                     *                                       &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *                                     &lt;/sequence>
                     *                                   &lt;/restriction>
                     *                                 &lt;/complexContent>
                     *                               &lt;/complexType>
                     *                             &lt;/element>
                     *                             &lt;element name="PostalCode">
                     *                               &lt;complexType>
                     *                                 &lt;complexContent>
                     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                                     &lt;sequence>
                     *                                       &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *                                     &lt;/sequence>
                     *                                   &lt;/restriction>
                     *                                 &lt;/complexContent>
                     *                               &lt;/complexType>
                     *                             &lt;/element>
                     *                           &lt;/sequence>
                     *                         &lt;/restriction>
                     *                       &lt;/complexContent>
                     *                     &lt;/complexType>
                     *                   &lt;/element>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "administrativeAreaName",
                        "subAdministrativeArea"
                    })
                    public static class AdministrativeArea {

                        @XmlElement(name = "AdministrativeAreaName", required = true)
                        protected Object administrativeAreaName;
                        @XmlElement(name = "SubAdministrativeArea", required = true)
                        protected Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea subAdministrativeArea;

                        /**
                         * Gets the value of the administrativeAreaName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Object }
                         *     
                         */
                        public Object getAdministrativeAreaName() {
                            return administrativeAreaName;
                        }

                        /**
                         * Sets the value of the administrativeAreaName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Object }
                         *     
                         */
                        public void setAdministrativeAreaName(Object value) {
                            this.administrativeAreaName = value;
                        }

                        /**
                         * Gets the value of the subAdministrativeArea property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea }
                         *     
                         */
                        public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea getSubAdministrativeArea() {
                            return subAdministrativeArea;
                        }

                        /**
                         * Sets the value of the subAdministrativeArea property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea }
                         *     
                         */
                        public void setSubAdministrativeArea(Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea value) {
                            this.subAdministrativeArea = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="SubAdministrativeAreaName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                         *         &lt;element name="Locality">
                         *           &lt;complexType>
                         *             &lt;complexContent>
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                 &lt;sequence>
                         *                   &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                         *                   &lt;element name="Thoroughfare">
                         *                     &lt;complexType>
                         *                       &lt;complexContent>
                         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                           &lt;sequence>
                         *                             &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                         *                           &lt;/sequence>
                         *                         &lt;/restriction>
                         *                       &lt;/complexContent>
                         *                     &lt;/complexType>
                         *                   &lt;/element>
                         *                   &lt;element name="PostalCode">
                         *                     &lt;complexType>
                         *                       &lt;complexContent>
                         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                           &lt;sequence>
                         *                             &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                         *                           &lt;/sequence>
                         *                         &lt;/restriction>
                         *                       &lt;/complexContent>
                         *                     &lt;/complexType>
                         *                   &lt;/element>
                         *                 &lt;/sequence>
                         *               &lt;/restriction>
                         *             &lt;/complexContent>
                         *           &lt;/complexType>
                         *         &lt;/element>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "subAdministrativeAreaName",
                            "locality"
                        })
                        public static class SubAdministrativeArea {

                            @XmlElement(name = "SubAdministrativeAreaName", required = true)
                            protected Object subAdministrativeAreaName;
                            @XmlElement(name = "Locality", required = true)
                            protected Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality locality;

                            /**
                             * Gets the value of the subAdministrativeAreaName property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link Object }
                             *     
                             */
                            public Object getSubAdministrativeAreaName() {
                                return subAdministrativeAreaName;
                            }

                            /**
                             * Sets the value of the subAdministrativeAreaName property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link Object }
                             *     
                             */
                            public void setSubAdministrativeAreaName(Object value) {
                                this.subAdministrativeAreaName = value;
                            }

                            /**
                             * Gets the value of the locality property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality }
                             *     
                             */
                            public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality getLocality() {
                                return locality;
                            }

                            /**
                             * Sets the value of the locality property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality }
                             *     
                             */
                            public void setLocality(Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality value) {
                                this.locality = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType>
                             *   &lt;complexContent>
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *       &lt;sequence>
                             *         &lt;element name="LocalityName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                             *         &lt;element name="Thoroughfare">
                             *           &lt;complexType>
                             *             &lt;complexContent>
                             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *                 &lt;sequence>
                             *                   &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                             *                 &lt;/sequence>
                             *               &lt;/restriction>
                             *             &lt;/complexContent>
                             *           &lt;/complexType>
                             *         &lt;/element>
                             *         &lt;element name="PostalCode">
                             *           &lt;complexType>
                             *             &lt;complexContent>
                             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *                 &lt;sequence>
                             *                   &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                             *                 &lt;/sequence>
                             *               &lt;/restriction>
                             *             &lt;/complexContent>
                             *           &lt;/complexType>
                             *         &lt;/element>
                             *       &lt;/sequence>
                             *     &lt;/restriction>
                             *   &lt;/complexContent>
                             * &lt;/complexType>
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "localityName",
                                "thoroughfare",
                                "postalCode"
                            })
                            public static class Locality {

                                @XmlElement(name = "LocalityName", required = true)
                                protected Object localityName;
                                @XmlElement(name = "Thoroughfare", required = true)
                                protected Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare thoroughfare;
                                @XmlElement(name = "PostalCode", required = true)
                                protected Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode postalCode;

                                /**
                                 * Gets the value of the localityName property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Object }
                                 *     
                                 */
                                public Object getLocalityName() {
                                    return localityName;
                                }

                                /**
                                 * Sets the value of the localityName property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Object }
                                 *     
                                 */
                                public void setLocalityName(Object value) {
                                    this.localityName = value;
                                }

                                /**
                                 * Gets the value of the thoroughfare property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare }
                                 *     
                                 */
                                public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare getThoroughfare() {
                                    return thoroughfare;
                                }

                                /**
                                 * Sets the value of the thoroughfare property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare }
                                 *     
                                 */
                                public void setThoroughfare(Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare value) {
                                    this.thoroughfare = value;
                                }

                                /**
                                 * Gets the value of the postalCode property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode }
                                 *     
                                 */
                                public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode getPostalCode() {
                                    return postalCode;
                                }

                                /**
                                 * Sets the value of the postalCode property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode }
                                 *     
                                 */
                                public void setPostalCode(Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode value) {
                                    this.postalCode = value;
                                }


                                /**
                                 * <p>Java class for anonymous complex type.
                                 * 
                                 * <p>The following schema fragment specifies the expected content contained within this class.
                                 * 
                                 * <pre>
                                 * &lt;complexType>
                                 *   &lt;complexContent>
                                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                                 *       &lt;sequence>
                                 *         &lt;element name="PostalCodeNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                                 *       &lt;/sequence>
                                 *     &lt;/restriction>
                                 *   &lt;/complexContent>
                                 * &lt;/complexType>
                                 * </pre>
                                 * 
                                 * 
                                 */
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "postalCodeNumber"
                                })
                                public static class PostalCode {

                                    @XmlElement(name = "PostalCodeNumber", required = true)
                                    protected Object postalCodeNumber;

                                    /**
                                     * Gets the value of the postalCodeNumber property.
                                     * 
                                     * @return
                                     *     possible object is
                                     *     {@link Object }
                                     *     
                                     */
                                    public Object getPostalCodeNumber() {
                                        return postalCodeNumber;
                                    }

                                    /**
                                     * Sets the value of the postalCodeNumber property.
                                     * 
                                     * @param value
                                     *     allowed object is
                                     *     {@link Object }
                                     *     
                                     */
                                    public void setPostalCodeNumber(Object value) {
                                        this.postalCodeNumber = value;
                                    }

                                }


                                /**
                                 * <p>Java class for anonymous complex type.
                                 * 
                                 * <p>The following schema fragment specifies the expected content contained within this class.
                                 * 
                                 * <pre>
                                 * &lt;complexType>
                                 *   &lt;complexContent>
                                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                                 *       &lt;sequence>
                                 *         &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                                 *       &lt;/sequence>
                                 *     &lt;/restriction>
                                 *   &lt;/complexContent>
                                 * &lt;/complexType>
                                 * </pre>
                                 * 
                                 * 
                                 */
                                @XmlAccessorType(XmlAccessType.FIELD)
                                @XmlType(name = "", propOrder = {
                                    "thoroughfareName"
                                })
                                public static class Thoroughfare {

                                    @XmlElement(name = "ThoroughfareName", required = true)
                                    protected Object thoroughfareName;

                                    /**
                                     * Gets the value of the thoroughfareName property.
                                     * 
                                     * @return
                                     *     possible object is
                                     *     {@link Object }
                                     *     
                                     */
                                    public Object getThoroughfareName() {
                                        return thoroughfareName;
                                    }

                                    /**
                                     * Sets the value of the thoroughfareName property.
                                     * 
                                     * @param value
                                     *     allowed object is
                                     *     {@link Object }
                                     *     
                                     */
                                    public void setThoroughfareName(Object value) {
                                        this.thoroughfareName = value;
                                    }

                                }

                            }

                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "coordinates"
            })
            public static class Point {

                @XmlElement(required = true)
                protected Object coordinates;

                /**
                 * Gets the value of the coordinates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getCoordinates() {
                    return coordinates;
                }

                /**
                 * Sets the value of the coordinates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setCoordinates(Object value) {
                    this.coordinates = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="request" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "request"
        })
        public static class Status {

            @XmlElement(required = true)
            protected Object code;
            @XmlElement(required = true)
            protected Object request;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setCode(Object value) {
                this.code = value;
            }

            /**
             * Gets the value of the request property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getRequest() {
                return request;
            }

            /**
             * Sets the value of the request property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setRequest(Object value) {
                this.request = value;
            }

        }

    }

}
