//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 10:39:11 AM BST 
//


package google.geocodingservice.geocoder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the google.geocodingservice.geocoder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: google.geocodingservice.geocoder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kml }
     * 
     */
    public Kml createKml() {
        return new Kml();
    }

    /**
     * Create an instance of {@link Kml.Response }
     * 
     */
    public Kml.Response createKmlResponse() {
        return new Kml.Response();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark }
     * 
     */
    public Kml.Response.Placemark createKmlResponsePlacemark() {
        return new Kml.Response.Placemark();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails }
     * 
     */
    public Kml.Response.Placemark.AddressDetails createKmlResponsePlacemarkAddressDetails() {
        return new Kml.Response.Placemark.AddressDetails();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country createKmlResponsePlacemarkAddressDetailsCountry() {
        return new Kml.Response.Placemark.AddressDetails.Country();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea createKmlResponsePlacemarkAddressDetailsCountryAdministrativeArea() {
        return new Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea createKmlResponsePlacemarkAddressDetailsCountryAdministrativeAreaSubAdministrativeArea() {
        return new Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality createKmlResponsePlacemarkAddressDetailsCountryAdministrativeAreaSubAdministrativeAreaLocality() {
        return new Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality();
    }

    /**
     * Create an instance of {@link Kml.Response.Status }
     * 
     */
    public Kml.Response.Status createKmlResponseStatus() {
        return new Kml.Response.Status();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.Point }
     * 
     */
    public Kml.Response.Placemark.Point createKmlResponsePlacemarkPoint() {
        return new Kml.Response.Placemark.Point();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare createKmlResponsePlacemarkAddressDetailsCountryAdministrativeAreaSubAdministrativeAreaLocalityThoroughfare() {
        return new Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.Thoroughfare();
    }

    /**
     * Create an instance of {@link Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode }
     * 
     */
    public Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode createKmlResponsePlacemarkAddressDetailsCountryAdministrativeAreaSubAdministrativeAreaLocalityPostalCode() {
        return new Kml.Response.Placemark.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.PostalCode();
    }

}
