// Ya Compiler to C++ 15.01.25 06:36:59 Ya
// Cenas.Cpp <- example1.Ya 2016.03.15 09:45:51

00

// complete with 1 fatal errors, 10 errors, 1 warnings, 0 messages
// 0: warning: Module "example1.Ya" must be started by '@example1.Ya'
// At: a : 0;
// 1: error: Undefined ident 'a'
// At: a : 0;
// 2: error: Appropriate 'e ? e:e' alike operator ':' with compatible args not found
// At: 
// 3: error: Undefined ident 'b'
// At: b : "ola";
// 4: error: Appropriate 'e ? e:e' alike operator ':' with compatible args not found
// At: 
// 5: error: Undefined ident 'f'
// At: f (b) : void {
// 6: error: Undefined ident 'b'
// At: f (b) : void {
// 7: error: Appropriate function '' with compatible args not found
// At: f (b) : void {
// 8: error: Undefined ident 'void'
// At: f (b) : void {
// 9: error: Appropriate 'e ? e:e' alike operator ':' with compatible args not found
// At: 
// 10: error: Only tabulations are allowed at start of lines, no spaces and characters in range 0h..1Fh
// At: 
// 11: fatal error: Internal error. Code is not implemented yet at 'Ya/YaLexer.Cpp' line 189

// At: 
